### ISSUE TITLE
Linker issue: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by vol24pl** [bitrise-steplib/steps-xcode-test#136]
Hello!

For specific libraries this error occurs when using `xcode-test` on Bitrise CLI @Xcode11. It's a hit or miss with different libs. Libs that caused this error are:

* Google Maps SDK via CocoaPods
* Google Maps SDK via manual install
* https://github.com/zxingify/zxingify-objc

Error message:
```
❌  ld: symbol(s) not found for architecture x86_64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

* When building locally everything works as expected.
* When connecting remotely to the CI machine, opening xcode from there and building/testing/archiving the version everything works as expected.

The only place where this issue happens is the actual step `xcode-test` via Bitrise CLI. I've checked Catalina as well as Mojave for Xcode 11. Same issue. When I remove the libs, the issue's instantly gone.

Is this something that you can address? If it can be build locally I see no reason for it to not work on the Bitrise CLI.

**Comment by bitce** [comment]
Hi @vol24pl!

Thank you so much for the detailed report. Can you please share a build URL and enable Support Access for us so we can investigate this?

**Comment by vol24pl** [comment]
Hi :)

Google Maps manually integrated:
https://app.bitrise.io/build/7ec963172e6e3040#?tab=log
Google Maps integrated through the Cocoapods:
https://app.bitrise.io/build/d64336c1e291dac1#?tab=log

Support should be enabled

**Comment by vol24pl** [comment]
Any updates?

**Comment by bmarcall** [comment]
I'm waiting too.

**Comment by non-binary** [comment]
Hi @vol24pl @bmarcall 

Thank you for your patience and I'm sorry for how long this has taken until now.

This has been escalated to our L3 support team for further investigation.

We will follow-up as soon as I've heard back from them.

Kind regards,
Luna

**Comment by non-binary** [comment]
Hi @vol24pl @bmarcall,

I talked to L3 support. Here is what was said: 😸 

The only thing they could notice is that you have no configuration specified in his build. More detail:

Xcode works 2 way:
1) when you start the IDE and running builds/tests within IDE
2) using command line tool (xcodebuild) to run builds/tests without the IDE itself.

- When user uses method 1, then xcode gets the configuration from the scheme only

![stress-test_xcodeproj-2](https://user-images.githubusercontent.com/6799989/78026690-0a7ce780-732a-11ea-92f1-be5f76895235.png)

- When the user uses method 2, xcodebuild gets the configuration from the configuration settings

![stress-test_xcodeproj](https://user-images.githubusercontent.com/6799989/78026711-17014000-732a-11ea-9836-254808817a2e.png)

in both cases configuration can be overridden by specifying configuration in (xcode-archive, xcode-test, etc... steps.

They checked the build log and there is no configuration specified. Please try setting configuration in the step or in your project (whatever you prefer), and re-run the build.

The reason I think it might fixes the issue is because project component linking and build parameters can depend on configuration.

Please let us know if this fixes the problem for you.

Kind regards and stay safe,
Luna

**Comment by vol24pl** [comment]
As Cocoapods generates the `xcworkspace` and I need to change by hand:

**FROM**: "Use `Realese` for command-line builds"
**TO**: "Use `MyConfig` for command-line builds"

Do you know how I can preconfigure that in `Podfile`? This would help me a lot.

Also can you tell me how can I choose config in `xcode-test` step?

**Comment by kylebrowning** [comment]
Im having this error as well. :(

**Comment by jeffveleze** [comment]
I'm having this issue and i do have Release configuration specified :/

**Comment by kylebrowning** [comment]
For me the issued seemed to be that my bitrise build step was set to Always latest, which is a legacy deprecated setting. Setting it specifically to 1.x.x resolved this issue.

**Comment by jeffveleze** [comment]
Hey @kylebrowning thanks for contribuiting, could you provide a llitle bit more of information about where that setting would be? Thanks!

**Comment by kylebrowning** [comment]
@jeffveleze In the workflow builder, where you choose the Xcode test step. Theres a version you choose on the right hand side.
